org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14
fabric_version=0.119.4+1.21.4
loom_version=1.11.8
mixinextras_version=0.5.4
cloth_config_version=17.0.144
jna_version=5.17.0
commons_io_version=2.20.0
lombok_version=1.18.38

maven_group=padej.soup
archives_base_name=soupvisuals
mod_version=3.1.0
